# Generated by Django 4.1.2 on 2023-03-01 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('second_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[(1, 'Admin'), (2, 'Dean'), (3, 'HOD'), (4, 'HEP'), (5, 'Teacher')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('В архиве', 'archive'), ('Актуальный', 'actual'), ('Отправлен на доработку', 'revise'), ('Отклонён', 'rejected'), ('В процессе составления', 'making'), ('В процессе редакции', 'redaction'), ('Составлен', 'made'), ('Согласован', 'conformed'), ('Утверждён', 'approved')], default=('В процессе составления', 'making'), max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_xml', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.link')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
