# Generated by Django 4.0 on 2022-04-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('second_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('В архиве', 'archive'), ('Актуальный', 'actual'), ('Отправлен на доработку', 'revise'), ('Отклонён', 'rejected'), ('В процессе составления', 'making'), ('В процессе редакции', 'redaction'), ('Составлен', 'made'), ('Согласован', 'conformed'), ('Утверждён', 'approved')], default=('В процессе составления', 'making'), max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.IntegerField(default=1)),
                ('section', models.IntegerField(default=1)),
                ('header', models.CharField(max_length=128)),
                ('classwork_hours', models.IntegerField()),
                ('homework_hours', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.link')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.status')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
