# Generated by Django 4.0 on 2022-04-05 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='semester',
        ),
    ]
