# Generated by Django 4.0 on 2022-04-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(default=1)),
                ('header', models.CharField(max_length=128)),
                ('classwork_hours', models.IntegerField()),
                ('homework_hours', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='theme',
            name='classwork_hours',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='description',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='header',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='homework_hours',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='section',
        ),
        migrations.AddField(
            model_name='theme',
            name='section_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.section'),
            preserve_default=False,
        ),
    ]
