# Generated by Django 4.0 on 2022-04-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0002_section_remove_theme_classwork_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='classwork_hours',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='section',
            name='homework_hours',
            field=models.IntegerField(default=2),
        ),
    ]
