# Generated by Django 4.1.2 on 2023-03-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0002_document_document_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
