# Generated by Django 4.0 on 2022-04-12 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0003_alter_section_classwork_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='section_id',
            new_name='module_id',
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.IntegerField(default=1)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.section')),
            ],
        ),
    ]
