# Generated by Django 4.1.2 on 2023-03-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0003_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(default='', max_length=512)),
                ('link_to_xml', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.link')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.customuser')),
            ],
        ),
    ]
