# Generated by Django 4.0 on 2022-04-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0004_rename_section_id_theme_module_id_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section',
        ),
    ]
