# Generated by Django 4.0 on 2022-04-12 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0005_remove_section_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='module',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='module_id',
        ),
        migrations.AddField(
            model_name='module',
            name='theme_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.theme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='module_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='document_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.document'),
            preserve_default=False,
        ),
    ]
