# Generated by Django 4.1.2 on 2023-03-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0005_document_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='program_code',
            field=models.CharField(default='', max_length=512),
        ),
    ]
