# Generated by Django 4.0 on 2022-04-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0007_section_theme_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
