# Generated by Django 4.0 on 2022-04-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0008_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='theme',
            field=models.IntegerField(auto_created=True, default=1, unique=True),
        ),
    ]
