# Generated by Django 4.0 on 2022-04-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0009_alter_theme_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='theme',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
