# Generated by Django 4.0 on 2022-04-12 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0010_alter_theme_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='theme',
        ),
    ]
