# Generated by Django 4.0 on 2022-04-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0011_remove_theme_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
