# Generated by Django 4.0 on 2022-04-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0012_section_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='number',
        ),
    ]
