# Generated by Django 4.0 on 2022-04-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0013_remove_section_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
