# Generated by Django 4.0 on 2022-04-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0015_section_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=128)),
                ('profile_name', models.CharField(max_length=128)),
                ('program_code', models.CharField(max_length=128)),
                ('year_start', models.IntegerField(default=2022)),
                ('year_end', models.IntegerField(default=2022)),
            ],
        ),
    ]
