# Generated by Django 4.0 on 2022-04-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0016_workprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='workprogram',
            name='program_name',
        ),
        migrations.CreateModel(
            name='TimePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classwork_hours', models.IntegerField(default=2)),
                ('homework_hours', models.IntegerField(default=2)),
                ('intensity_ZET', models.IntegerField(default=2)),
                ('program_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.programnames')),
            ],
        ),
        migrations.AddField(
            model_name='programnames',
            name='work_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.workprogram'),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=128)),
                ('time_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.timeplan')),
            ],
        ),
    ]
