# Generated by Django 4.0 on 2022-04-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0017_programnames_remove_workprogram_program_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
