# Generated by Django 4.0 on 2022-04-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0018_delete_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programnames',
            name='program_name',
            field=models.CharField(max_length=512),
        ),
    ]
