# Generated by Django 4.0 on 2022-04-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0019_alter_programnames_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='program_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='excel_to_doc_parser.programnames'),
            preserve_default=False,
        ),
    ]
