# Generated by Django 4.0 on 2022-04-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0020_remove_document_name_document_program_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workprogram',
            old_name='profile_name',
            new_name='program_name',
        ),
    ]
