# Generated by Django 4.1.2 on 2022-11-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_doc_parser', '0022_rename_program_name_workprogram_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Dean'), (3, 'HOD'), (4, 'HEP'), (5, 'Teacher')], max_length=128),
        ),
    ]
